### ISSUE TITLE
New Build is Broken?

### ISSUE THREAD

**Issue by JeremyRubin** [ruby/ruby-docker-images#27]
I use the 2.7 alpine ruby image for my GH pages jekyll site and the new releases broke my build. 

see https://github.com/JeremyRubin/rubin.io/runs/4370521856?check_suite_focus=true

```
30
Status: Downloaded newer image for ruby:2.7-alpine
```

```
51
LoadError: Error loading shared library libffi.so.7: No such file or directory (needed by /github/workspace/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.3/lib/ffi_c.so) - /github/workspace/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.3/lib/ffi_c.so
52
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.3/lib/ffi.rb:5:in `require'
53
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.3/lib/ffi.rb:5:in `rescue in <top (required)>'
54
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.3/lib/ffi.rb:2:in `<top (required)>'
55
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `require'
56
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'
57
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
58
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
59
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `require'
60
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
61
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `require'
62
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
63
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `require'
64
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `<top (required)>'
65
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/exe/jekyll:8:in `require'
66
  /github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/exe/jekyll:8:in `<top (required)>'
67
  /github/workspace/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
68
  /github/workspace/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<top (required)>'
```

**Comment by hsbt** [comment]
`ruby:2.7-alpine` is not our image. It's maintained by https://github.com/docker-library/ruby

**Comment by JeremyRubin** [comment]
that's confusing 😛 my bad

**Comment by sneakers-the-rat** [comment]
@JeremyRubin had this same issue, i see you're on gh actions, was able to fix by invalidating caches and forcing a fresh reinstall/build :)
